### ISSUE TITLE
TODO Items

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#1]
- [x] Add proper README.md possibly with png of a page or two, could use new Rcpp Intro
- [ ] Rewrite or add lead to skeleton.Rmd to refer to rticles::pnas_article for help
- [ ] Add markdown example for two-column figure
- [ ] Add table example
- [x] Expand bib file adding PeerJ
- [ ] Give proper credit to PNAS and rticles packages, 
    - [ ] GPL-3 copyright from rticles carried over, 
    - [ ] unclear what PNAS / Overleaf copyright terms are besides standard (liberal) TeX / TUG licensing
- [ ] Ideally make all useful features accessible from yaml with fallbacks:
   - [ ] Watermark yes/no
   - [ ] doi entry, can be used as CRAN package URL
   - [ ] Package name used in footer left and right (currently Rcpp hardcoded)
- [ ] A few PNAS sillynesses have been removed such as which author matters more, which conflicts of interest arose, what significance the paper has etc.  This could be revisited but as a template for vignettes / paper drafts seems fine
- [ ] Could possibly relax use of the two-col template from PNAS (but 'KISS' rules: simpler as is)

**Comment by coatless** [comment]
~~1. Are you okay with using the `tint` README as a shell with a few modifications?~~
2. There probably should be a rewrite of the `skeleton.Rmd` to cut down on the PNAS specific lingo (after all Pinp Is Not PNAS)
3. Not sure about the approach for this one outside of creating a specific latex macro for it. (See the safe columns hack in [uiucthemes::beamer_illinois](https://github.com/coatless/uiucthemes/blob/d1565f4359374990b9a6772c4e61355b26c043b9/inst/rmarkdown/templates/beamer_illinois/resources/template.tex#L300-L308).)
4. I'll add that in. Are you okay with a contingency table? (e.g. 3 x 3 with numbers being in the inner  2x2?
5. I'll toss in the PeerJ citation for Extending... Or, this could wait until TAS goes live?
6. LaTeX header, README, roxygen2 documentation, anything else? 
    - [PNAS' main style](http://www.pnas.org/site/misc/pnas-new.cls) is covered by LaTeX Project Public License >= version 1.3 
7. Let me think about that...
8. Agreed. I don't really feel like that is needed at this point.
9. Two-col first and then enable one-col. The change-over is straightforward according to the [`rticles::pnas_article()`](https://github.com/rstudio/rticles/blob/93ddb6b53db72e3cb8b29aa77c81c089551fc62b/inst/rmarkdown/templates/pnas_article/resources/template.tex#L76)

**Comment by eddelbuettel** [comment]
~~1. README: Yes, I'll do that, and link to our PeerJ piece and show a page or two.~~
2. Skeleton: Probably.
3. Two-col Figure:  Do we need a new macro? For PeerJ we just use `figure*`.
4. Table:  Knitr can probably do it.  See the commented-out PNAS example in skeleton. Possible Pandoc issue?
5. PeerJ cite:  I'll add it when I do a first README.  We can switch to TAS / add it once live.
6. Credits. Yep.  In README too.
7. YAML:  That is the only actual work.  We also need to look at pnas_article again and pnas-new.cls
8. Simpler:  Good.
9. Two and One Col:  Ok

This format sucketh.  New tickets for detailed discussion?

**Comment by coatless** [comment]
Okay. I'm splitting up the issues.

**Comment by eddelbuettel** [comment]
Please coordinate informally before you do. I am not a fan of James in hurricane mode filing 37 distinct issues at once.

**Comment by coatless** [comment]
I'm envisioning breaking this issue into 5 separate issues: 

Issue 1: Rewrite of the skeleton.Rmd that involves removing the PNAS specific language, showing how to add 2 column figure via LaTeX's `figure*`, adding a table example using `knitr::kable()`.

Issue 2: Adding to documentation proper acknowledgements to `PNAS` and `rticles`.

Issue 3: Enabling useful features.

Issue 4: Removing extra PNAS content in the `template.tex`

Issue 5: Adding in a one-col format.
